package com.mygdx.aoc.android;

import android.os.Bundle;
import android.util.Log;

import com.badlogic.gdx.backends.android.AndroidApplication;
import com.badlogic.gdx.backends.android.AndroidApplicationConfiguration;
import com.google.android.gms.ads.AdListener;
import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.InterstitialAd;

import com.mygdx.aoc.AgeOfCapybaras;

public class AndroidLauncher extends AndroidApplication implements com.admob.AdsController {


    //    A class where the elapsed time between the opening and closing of an Ad can be retrieved.
    private class MyAdListener extends AdListener {

        public long start = -1, end = -1;

        //        Opening event.
        @Override
        public void onAdOpened() {
            start = System.nanoTime();
            end = -1;
            super.onAdOpened();
        }

        //        Closing event.
        @Override
        public void onAdClosed() {
            end = System.nanoTime();
            System.out.println("Ad opened for " + elapsedTime() + "seconds");
            super.onAdClosed();
        }

        //        Calculates the elapsed time.
        public double elapsedTime() {
            if (end < 0 || start < 0)
                return -1;
            long elapsed = end - start;
            double seconds = (double)elapsed / 1000000000.0; // Converting to seconds
            start = end = -1;
            return seconds;
        }
    }

    private InterstitialAd mInterstitialAd;
    private MyAdListener mAdListener = new MyAdListener();





//    public AdManager adM; // AdManager usage example

    @Override
    protected void onPause() {

//        adM.requestAd(); // AdManager usage example

        super.onPause();
        AgeOfCapybaras.onPause();
    }

    @Override
    protected void onResume() {
        super.onResume();

//        double time;                            //
//        adM.displayAd();                        //
//        time = adM.elapsedTime();               // AdManager usage example
//        if (time >= 20)                         //
//            Log.v("ETime", "Time = " + time);   //

        AgeOfCapybaras.onResume();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

//        Constructs an InterstitialAd object and set its ad unit ID.
        mInterstitialAd = new InterstitialAd(this);
        mInterstitialAd.setAdUnitId("ca-app-pub-3940256099942544/1033173712"); //This ID needs to be generated by AdMob.
        mInterstitialAd.setAdListener(mAdListener);

        AndroidApplicationConfiguration config = new AndroidApplicationConfiguration();
        config.useCompass = false;
        config.useAccelerometer = false;
        initialize(new AgeOfCapybaras(this), config);
    }

    @Override
    public void requestAd() {
//        Requests an ad.
        AdRequest adRequest = new AdRequest.Builder()
                .addTestDevice(AdRequest.DEVICE_ID_EMULATOR)
                .build();
//        Um id gerado para uma conta no AdMob deve ser colado no lugar de
//        AdRequest.DEVICE_ID_EMULATOR entre aspas quando o aplicativo estiver
//        pronto para ir para a Play Store.
        mInterstitialAd.loadAd(adRequest);
    }

    @Override
    public void displayAd() {
//        Checks that an ad is loaded and then display it.
        if (mInterstitialAd.isLoaded()) {
            mInterstitialAd.show();
        }
    }

    @Override
    //    Returns the elapsed time.
    public double elapsedTime() {
        return mAdListener.elapsedTime();
    }
}
