package com.mygdx.aoc.android;

import android.os.Bundle;

import com.badlogic.gdx.backends.android.AndroidApplication;
import com.badlogic.gdx.backends.android.AndroidApplicationConfiguration;
import com.google.android.gms.ads.AdListener;
import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.InterstitialAd;

import com.mygdx.aoc.AgeOfCapybaras;
import com.mygdx.aoc.User;

import java.math.BigDecimal;

public class AndroidLauncher extends AndroidApplication implements com.admob.AdsController {


    //    A class where the elapsed time between the opening and closing of an Ad can be retrieved.
    private class MyAdListener extends AdListener {

        public long start = -1, end = -1;

        //        Opening event.
        @Override
        public void onAdOpened() {
            start = System.nanoTime();
            end = -1;
            super.onAdOpened();
        }

        //        Closing event.
        @Override
        public void onAdClosed() {
            end = System.nanoTime();
            double eTime = elapsedTime();
            requestAd();
            if (eTime >= 20) {
                User.kps = User.kps.add(BigDecimal.ONE); // Bonus for watching the ad.
            }
            super.onAdClosed();
        }

        //        Calculates the elapsed time.
        public double elapsedTime() {
            if (end < 0 || start < 0)
                return -1;
            long elapsed = end - start;
            double seconds = (double)elapsed / 1000000000.0; // Converting to seconds
            start = end = -1;
            return seconds;
        }
    }

    private InterstitialAd mInterstitialAd;
    private MyAdListener mAdListener = new MyAdListener();

    @Override
    protected void onPause() {
        super.onPause();
        AgeOfCapybaras.onPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        AgeOfCapybaras.onResume();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

//        Constructs an InterstitialAd object and set its ad unit ID.
        mInterstitialAd = new InterstitialAd(this);
        mInterstitialAd.setAdUnitId("ca-app-pub-3940256099942544/1033173712"); //This ID needs to be generated by AdMob.
        mInterstitialAd.setAdListener(mAdListener);

        AndroidApplicationConfiguration config = new AndroidApplicationConfiguration();
        config.useCompass = false;
        config.useAccelerometer = false;
        initialize(new AgeOfCapybaras(this), config);
    }

    @Override
    public void requestAd() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
//        Requests an ad.
                AdRequest adRequest = new AdRequest.Builder()
                        .addTestDevice(AdRequest.DEVICE_ID_EMULATOR)
                        .build();
//        An ID generated for an AdMob account must be pasted in
//        "AdRequest.DEVICE_ID_EMULATOR" place when the app is completed.
                mInterstitialAd.loadAd(adRequest);
            }
        });
    }

    @Override
    public void displayAd() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
//        Checks that an ad is loaded and then display it.
                if (mInterstitialAd.isLoaded()) {
                    mInterstitialAd.show();
                }
            }
        });
    }

    @Override
    //    Returns the elapsed time.
    public double elapsedTime() {
        return mAdListener.elapsedTime();
    }
}
